version: '3.9'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:11.1
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_USER=admin
      - MARIADB_PASSWORD=admin
      - MARIADB_DATABASE=thedoors_db
    volumes:
      - './db_data:/bitnami'
    restart: unless-stopped
  theDoors:
    image: docker.io/bitnami/laravel:10
    ports:
      - '8000:8000'
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USERNAME=admin
      - DB_PASSWORD=admin
      - DB_DATABASE=thedoors_db
    volumes:
      - './thedoors-data:/app'
    depends_on:
      - mariadb
    restart: unless-stopped
  phpmyadmin:
    image: docker.io/bitnami/phpmyadmin:5
    ports:
      - '8080:8080'
      - '443:8443'
    depends_on:
      - mariadb
    restart: unless-stopped